name = "terminal"

[theme.custom]
accent = "#bb7744"
panel_bg = "#222222"
surface0 = "#43492a"
surface1 = "#78824b"
surface_dim = "#1c1c1c"
overlay0 = "#666666"
overlay1 = "#c2c2b0"
text = "#d7c483"
subtext0 = "#c2c2b0"
mauve = "#bb7744"
green = "#5f875f"
yellow = "#c9a554"
red = "#b36d43"
blue = "#78824b"
teal = "#c9a554"
peach = "#b36d43"
